<?php
// Start output buffering to capture content
ob_start();
?>

<!-- Page Header -->
<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h1 class="h3 mb-0">ID Cards Management</h1>
        <p class="text-muted">Manage and generate resident ID cards</p>
    </div>
    <div>
        <button type="button" class="btn btn-info me-2" onclick="printAllIdCards()">
            <i class="fas fa-print"></i> Print All ID Cards
        </button>
        <button type="button" class="btn btn-success me-2" onclick="generateAllIdCards()">
            <i class="fas fa-magic"></i> Generate All ID Cards
        </button>
        <a href="id-cards.php?action=generate" class="btn btn-primary">
            <i class="fas fa-plus"></i> Generate New ID Card
        </a>
    </div>
</div>

<!-- Search and Filters -->
<div class="card mb-4">
    <div class="card-body">
        <form method="GET" action="id-cards.php" class="row g-3">
            <input type="hidden" name="action" value="index">
            
            <div class="col-md-4">
                <label for="search" class="form-label">Search</label>
                <input type="text" class="form-control" id="search" name="search" 
                       value="<?= htmlspecialchars($_GET['search'] ?? '') ?>" 
                       placeholder="Search by resident name or card number">
            </div>
            
            <div class="col-md-3">
                <label for="status" class="form-label">Status</label>
                <select class="form-select" id="status" name="status">
                    <option value="">All Status</option>
                    <option value="active" <?= ($_GET['status'] ?? '') === 'active' ? 'selected' : '' ?>>Active</option>
                    <option value="expired" <?= ($_GET['status'] ?? '') === 'expired' ? 'selected' : '' ?>>Expired</option>
                    <option value="cancelled" <?= ($_GET['status'] ?? '') === 'cancelled' ? 'selected' : '' ?>>Cancelled</option>
                </select>
            </div>
            
            <div class="col-md-3">
                <label for="barangay" class="form-label">Barangay</label>
                <select class="form-select" id="barangay" name="barangay_id">
                    <option value="">All Barangays</option>
                    <?php foreach ($barangays as $barangay): ?>
                        <option value="<?= $barangay['id'] ?>" 
                                <?= ($_GET['barangay_id'] ?? '') == $barangay['id'] ? 'selected' : '' ?>>
                            <?= htmlspecialchars($barangay['name']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            
            <div class="col-md-2">
                <label class="form-label">&nbsp;</label>
                <div>
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-search"></i> Search
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- ID Cards Table -->
<div class="card">
    <div class="card-header">
        <h5 class="card-title mb-0">
            <i class="fas fa-id-card"></i> ID Cards (<?= $totalCards ?>)
        </h5>
    </div>
    <div class="card-body">
        <?php if (!empty($idCards)): ?>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Card Number</th>
                            <th>Resident</th>
                            <th>Barangay</th>
                            <th>Issue Date</th>
                            <th>Expiry Date</th>
                            <th>Status</th>
                            <th>Generated By</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($idCards as $card): ?>
                            <tr>
                                <td>
                                    <strong><?= htmlspecialchars($card['card_number']) ?></strong>
                                </td>
                                <td>
                                    <div>
                                        <strong><?= htmlspecialchars($card['resident_name']) ?></strong>
                                        <br>
                                        <small class="text-muted">
                                            <?= htmlspecialchars($card['resident_details']) ?>
                                        </small>
                                    </div>
                                </td>
                                <td><?= htmlspecialchars($card['barangay_name']) ?></td>
                                <td><?= date('M d, Y', strtotime($card['issue_date'])) ?></td>
                                <td>
                                    <?php if ($card['expiry_date']): ?>
                                        <?= date('M d, Y', strtotime($card['expiry_date'])) ?>
                                    <?php else: ?>
                                        <span class="text-muted">No expiry</span>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?php
                                    $statusClass = '';
                                    $statusText = ucfirst($card['status']);
                                    
                                    switch ($card['status']) {
                                        case 'active':
                                            $statusClass = 'bg-success';
                                            break;
                                        case 'expired':
                                            $statusClass = 'bg-warning';
                                            break;
                                        case 'cancelled':
                                            $statusClass = 'bg-danger';
                                            break;
                                    }
                                    ?>
                                    <span class="badge <?= $statusClass ?>"><?= $statusText ?></span>
                                </td>
                                <td><?= htmlspecialchars($card['generated_by_name']) ?></td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a href="id-cards.php?action=view&id=<?= $card['id'] ?>" 
                                           class="btn btn-sm btn-outline-primary" title="View">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a href="id-cards.php?action=print&id=<?= $card['id'] ?>" 
                                           class="btn btn-sm btn-outline-secondary" title="Print" target="_blank">
                                            <i class="fas fa-print"></i>
                                        </a>
                                        <?php if ($card['status'] === 'active'): ?>
                                            <a href="id-cards.php?action=renew&id=<?= $card['id'] ?>" 
                                               class="btn btn-sm btn-outline-warning" title="Renew">
                                                <i class="fas fa-sync-alt"></i>
                                            </a>
                                        <?php endif; ?>
                                        <?php if (hasPermission('id_card_generation')): ?>
                                            <button type="button" class="btn btn-sm btn-outline-danger" 
                                                    onclick="cancelCard(<?= $card['id'] ?>)" title="Cancel">
                                                <i class="fas fa-times"></i>
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            
            <!-- Pagination -->
            <?php if ($pagination['totalPages'] > 1): ?>
                <nav aria-label="ID Cards pagination" class="mt-4">
                    <ul class="pagination justify-content-center">
                        <?php if ($pagination['currentPage'] > 1): ?>
                            <li class="page-item">
                                <a class="page-link" href="?action=index&page=<?= $pagination['currentPage'] - 1 ?><?= $queryString ?>">
                                    Previous
                                </a>
                            </li>
                        <?php endif; ?>
                        
                        <?php for ($i = $pagination['startPage']; $i <= $pagination['endPage']; $i++): ?>
                            <li class="page-item <?= $i == $pagination['currentPage'] ? 'active' : '' ?>">
                                <a class="page-link" href="?action=index&page=<?= $i ?><?= $queryString ?>"><?= $i ?></a>
                            </li>
                        <?php endfor; ?>
                        
                        <?php if ($pagination['currentPage'] < $pagination['totalPages']): ?>
                            <li class="page-item">
                                <a class="page-link" href="?action=index&page=<?= $pagination['currentPage'] + 1 ?><?= $queryString ?>">
                                    Next
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </nav>
            <?php endif; ?>
            
        <?php else: ?>
            <div class="text-center text-muted py-5">
                <i class="fas fa-id-card fa-3x mb-3"></i>
                <h5>No ID Cards Found</h5>
                <p>No ID cards match your search criteria.</p>
                <a href="id-cards.php?action=generate" class="btn btn-primary">
                    <i class="fas fa-plus"></i> Generate First ID Card
                </a>
            </div>
        <?php endif; ?>
    </div>
</div>

<!-- Cancel Card Modal -->
<div class="modal fade" id="cancelCardModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Cancel ID Card</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to cancel this ID card? This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form method="POST" action="id-cards.php" style="display: inline;">
                    <input type="hidden" name="action" value="cancel">
                    <input type="hidden" name="card_id" id="cancelCardId">
                    <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
                    <button type="submit" class="btn btn-danger">Yes, Cancel Card</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
function cancelCard(cardId) {
    document.getElementById('cancelCardId').value = cardId;
    new bootstrap.Modal(document.getElementById('cancelCardModal')).show();
}

function generateAllIdCards() {
    if (confirm('This will generate ID cards for ALL residents who don\'t have active ID cards. This may take a few moments. Continue?')) {
        // Show loading state
        const button = event.target;
        const originalText = button.innerHTML;
        button.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Generating...';
        button.disabled = true;
        
        // Make AJAX request
        fetch('id-cards.php?action=generate-all', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                csrf_token: '<?= $csrf_token ?>'
            })
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                alert(`Successfully generated ${data.generated} ID cards!`);
                location.reload(); // Refresh the page to show new cards
            } else {
                alert('Error: ' + data.message);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('An error occurred while generating ID cards.');
        })
        .finally(() => {
            // Restore button state
            button.innerHTML = originalText;
            button.disabled = false;
        });
    }
}

function printAllIdCards() {
    if (confirm('This will open all active ID cards in a new window for printing. Continue?')) {
        // Open bulk print page in new window
        window.open('id-cards.php?action=print-all', '_blank', 'width=1200,height=800');
    }
}
</script>

<?php
// Get the buffered content
$content = ob_get_clean();

// Include the main layout
require_once 'views/layouts/main.php';
?> 